Repository Lammer-FH/boutique-hotel-technikum-2024-ae, pull requests merged in 2024-06, with the labels that each got.

#18 Added run config for DB, JavaApplication and Website
  .run/HotelApplication.run.xml
  .run/HotelDB.run.xml
  .run/HotelWebsite.run.xml
Labels: enhancement

#17 Anpassungen der Doku aus Feedback in LV
  API_specification.md
  Paperprototype.pdf
  api_specification.yaml
  db-design.md
Labels: documentation

#21 refactored vue component structure
  client/README.md
  client/src/App.vue
  client/src/assets/.gitkeep
  client/src/assets/AddressComponent.vue
  client/src/assets/CompanyName.vue
  client/src/assets/FBNumber.vue
  client/src/assets/HotelName.vue
  client/src/assets/MailComponent.vue
  client/src/assets/PhoneComponent.vue
  client/src/assets/UIDNumber.vue
  client/src/assets/index.js
  client/src/atoms/BaseButton.vue
  client/src/atoms/MenuButton.vue
  client/src/atoms/ToastComponent.vue
  client/src/atoms/index.js
  client/src/molecules/.gitkeep
  client/src/molecules/MessageArea.vue
  client/src/molecules/index.js
  client/src/organisms/.gitkeep
  client/src/organisms/HotelFooter.vue
  client/src/organisms/HotelMenu.vue
  client/src/organisms/index.js
  client/src/pages/AGBPage.vue
  client/src/pages/ContactPage.vue
  client/src/pages/DataProtectionPage.vue
  client/src/pages/DatenschutzPage.vue
  client/src/pages/ImpressumPage.vue
  client/src/pages/ImprintPage.vue
  client/src/pages/KontaktPage.vue
  client/src/pages/TermsAndConditionsPage.vue
  client/src/pages/index.js
  client/src/router/index.js
Labels: refactoring

#22 Enhancement/12 u2 hotelzimmerauswahl
  README.md
  api_specification.yaml
  client/.env
  client/package-lock.json
  client/package.json
  client/public/ImageNotFound.jpg
  client/src/atoms/CharacteristicComponent.vue
  client/src/atoms/ImageComponent.vue
  client/src/atoms/MainButton.vue
  client/src/atoms/index.js
  client/src/molecules/CharacteristicsTable.vue
  client/src/molecules/DatePicker.vue
  client/src/molecules/RoomCard.vue
  client/src/molecules/index.js
  client/src/organisms/HotelMenu.vue
  client/src/organisms/RoomList.vue
  client/src/organisms/RoomSearch.vue
  client/src/organisms/index.js
  client/src/pages/RoomDetailsPage.vue
  client/src/pages/RoomsPage.vue
  client/src/pages/index.js
  client/src/router/index.js
  client/src/store/.gitkeep
  client/src/store/index.js
  client/src/store/useImageStore.js
  client/src/store/useRoomStore.js
  db-design.md
  server/boutique-hotel-technikum/pom.xml
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/controllers/ImageController.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/controllers/RoomController.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/dtos/CharacteristicDto.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/dtos/RoomDto.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/dtos/RoomImageDto.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/CharacteristicEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/RoomEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/RoomImageEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/objects/RoomResponseObject.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/services/ImageService.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/services/RoomService.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/sql/Seeder.sql
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/transformer/ITransformer.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/transformer/RoomTransformer.java
  server/boutique-hotel-technikum/src/main/resources/images/NoImage.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage1.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage2.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage3.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage4.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage5.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage6.jpg
  server/boutique-hotel-technikum/src/main/resources/images/RoomImage7.jpg
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/RoomControllerTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/RoomServiceTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/functional/ImageControllerIntegrationTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/functional/RoomControllerIntegrationTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/ImageControllerUnitTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/ImageServiceUnitTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/RoomControllerUnitTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/RoomServiceUnitTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/RoomTransformerUnitTests.java
Labels: enhancement

#23 Enhancement/13 u3 verfuegbarkeit pruefen
  api_specification.yaml
  client/src/atoms/FeedbackMessage.vue
  client/src/atoms/index.js
  client/src/molecules/DatePicker.vue
  client/src/organisms/RoomSearch.vue
  client/src/store/useRoomStore.js
  client/src/utils/dateUtils.js
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/controllers/RoomController.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/dtos/BookingDto.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/dtos/GuestDto.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/BookingEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/GuestEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/models/RoomEntity.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/repositories/RoomRepository.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/services/RoomService.java
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/sql/Seeder.sql
  server/boutique-hotel-technikum/src/main/java/com/example/boutiquehoteltechnikum/transformer/BookingTransformer.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/RoomControllerUnitTests.java
  server/boutique-hotel-technikum/src/test/java/com/example/boutiquehoteltechnikum/unit/RoomServiceUnitTests.java
Labels: enhancement
